# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
pod "FBSDKCoreKit"
pod "FBSDKShareKit"

target 'mashtag' do

end

target 'mashtagTests' do

end

